.github/workflows/repro.yml: sudo apt update -y
Fixes issue:
Setup ffmpeg for video capture

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
142
Error: Process completed with exit code 100.